### ISSUE TITLE
no module named REST_views

### ISSUE THREAD

**Issue by kevthehermit** [PUNCH-Cyber/YaraGuardian#41]
Installing on to a Ubuntu 16.04 vps. 
Run install.sh
install pip requirements
setup config.json

not using venv

python manage.py migrate

```
ubuntu@yara-guardian:~/YaraGuardian$ python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 398, in execute
    self.check()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 426, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/registry.py", line 75, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/urls.py", line 23, in check_resolver
    for pattern in resolver.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 417, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 410, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/ubuntu/YaraGuardian/YaraGuardian/urls.py", line 3, in <module>
    import YaraGuardian.API.urls
  File "/home/ubuntu/YaraGuardian/YaraGuardian/API/urls.py", line 7, in <module>
    import YaraGuardian.API.rules
  File "/home/ubuntu/YaraGuardian/YaraGuardian/API/rules.py", line 3, in <module>
    from rules.REST_views import (RulesetsListingView,
ImportError: No module named REST_views

```

**Comment by kevthehermit** [comment]
Solved - Python 3.x not 2.x
