### ISSUE TITLE
Failure to launch: "no attribute password_reset_confirm"

### ISSUE THREAD

**Issue by deadbits** [PUNCH-Cyber/YaraGuardian#58]
I followed the installation instructions for a Development environment, but when I go to run the first command `python manage.py migrate`, I receive a traceback that throws `AttributeError: module 'django.contrib.auth.views' has no attributes 'password_reset_confirm'`

Any help here would be great 👍 

Full traceback:
```
(YaraGuardian) zeroharbor :: /opt/YaraGuardian ‹master*› » python3.5 manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    execute_from_command_line(sys.argv)
  File "/home/adam/.local/share/virtualenvs/YaraGuardian-6kWGavhf/lib/python3.5/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/adam/.local/share/virtualenvs/YaraGuardian-6kWGavhf/lib/python3.5/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/adam/.local/share/virtualenvs/YaraGuardian-6kWGavhf/lib/python3.5/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/adam/.local/share/virtualenvs/YaraGuardian-6kWGavhf/lib/python3.5/site-packages/django/core/management/base.py", line 361, in execute
    self.check()
  File "/home/adam/.local/share/virtualenvs/YaraGuardian-6kWGavhf/lib/python3.5/site-packages/django/core/management/base.py", line 390, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/adam/.local/share/virtualenvs/YaraGuardian-6kWGavhf/lib/python3.5/site-packages/django/core/management/commands/migrate.py", line 65, in _run_checks
    issues.extend(super()._run_checks(**kwargs))
  File "/home/adam/.local/share/virtualenvs/YaraGuardian-6kWGavhf/lib/python3.5/site-packages/django/core/management/base.py", line 377, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/adam/.local/share/virtualenvs/YaraGuardian-6kWGavhf/lib/python3.5/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/adam/.local/share/virtualenvs/YaraGuardian-6kWGavhf/lib/python3.5/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/home/adam/.local/share/virtualenvs/YaraGuardian-6kWGavhf/lib/python3.5/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/home/adam/.local/share/virtualenvs/YaraGuardian-6kWGavhf/lib/python3.5/site-packages/django/urls/resolvers.py", line 398, in check
    for pattern in self.url_patterns:
  File "/home/adam/.local/share/virtualenvs/YaraGuardian-6kWGavhf/lib/python3.5/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/adam/.local/share/virtualenvs/YaraGuardian-6kWGavhf/lib/python3.5/site-packages/django/urls/resolvers.py", line 579, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/adam/.local/share/virtualenvs/YaraGuardian-6kWGavhf/lib/python3.5/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/adam/.local/share/virtualenvs/YaraGuardian-6kWGavhf/lib/python3.5/site-packages/django/urls/resolvers.py", line 572, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/adam/.local/share/virtualenvs/YaraGuardian-6kWGavhf/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/opt/YaraGuardian/YaraGuardian/urls.py", line 45, in <module>
    auth_views.password_reset_confirm, {'template_name': 'prelogin/ResetPassword.html'},
AttributeError: module 'django.contrib.auth.views' has no attribute 'password_reset_confirm'
```

**Comment by deadbits** [comment]
I worked around this by using the Docker installation instead of virtual environment. Not exactly a fix but it works for me at the very least.
